caridade/urls.py
from django.urls import path
from . import views

app_name = 'caridade'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('caridade/<int:pk>/', views.DetalhesView.as_view(), name='detalhes'),
]

enquetes/urls.py
from django.urls import path
from . import views

app_name = 'enquetes'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('encerradas/', views.EncerradasView.as_view(), name='encerradas'),
    path('enquete/<int:pk>/', views.DetalhesView.as_view(), name='detalhes'),
    path('enquete/<int:pk>/votacao/', views.VotacaoView.as_view(), name='votacao'),
    path('enquete/<int:pk>/resultado/', views.ResultadoView.as_view(), name='resultado'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('principal.urls')),
    path('admin/', admin.site.urls),
    path('enquetes/', include('enquetes.urls')),
    path('caridade/', include('caridade.urls')),
]

principal/urls.py
from django.urls import path
from . import views

app_name = 'principal'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

caridade/models.py
from django.db import models
from django.contrib.auth.models import User


class Evento(models.Model):
    nome = models.CharField(max_length=100)
    data_inicio = models.DateField('Data de início')
    data_fim = models.DateField('Data de encerramento')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

class Item(models.Model):
    imagem = models.ImageField(upload_to='imagem_item/', null=True, blank=True)
    descricao = models.CharField(max_length=50)
    valor = models.FloatField()
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE, default=1)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.descricao

class Reserva(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.item.descricao} reservado por: {self.usuario.username}"

enquetes/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Pergunta(models.Model):
    enunciado = models.CharField(max_length=150)
    data_pub = models.DateTimeField('Data de publicação')
    data_encerramento = models.DateField('Data de encerramento', null=True)
    def __str__(self):
        return self.enunciado
    def publicada_recentemente(self):
        marco_48h_passado = timezone.now() - datetime.timedelta(hours=48)
        agora = timezone.now()
        return (self.data_pub <= agora) and (self.data_pub >= marco_48h_passado)
    def total_de_votos(self):
        total = 0
        for alt in self.alternativa_set.all():
            total += alt.quant_votos
        return total
    def alternativas_ordenadas(self):
        return self.alternativa_set.order_by('-quant_votos')

    publicada_recentemente.admin_order_field = 'data_pub'
    publicada_recentemente.boolean = True
    publicada_recentemente.short_description = 'Recente?'


class Alternativa(models.Model):
    texto = models.CharField(max_length=80)
    quant_votos = models.IntegerField('Quantidade de votos', default=0)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    def __str__(self):
        return self.texto
    def porcentagem(self):
        return (self.quant_votos / self.pergunta.total_de_votos()) * 100

principal/models.py
from django.db import models

# Create your models here.

caridade/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from .models import Evento
from django.utils import timezone


class IndexView(View):
    def get(self, request, *args, **kwargs):
        #Se o evento já tiver sido encerrado, ele não aparece na lista
        lista_eventos = Evento.objects.filter(data_fim__gte = timezone.now())
        contexto = { 'lista_eventos' : lista_eventos}
        return render(request, 'caridade/index.html', contexto)


class DetalhesView(View):
    def get(self, request, *args, **kwargs):
        evento = get_object_or_404(Evento, pk=kwargs['pk'])
        contexto = {'evento': evento}
        return render(request, 'caridade/detalhes.html', contexto)

enquetes/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import View
from django.utils import timezone
from django.http import HttpResponseRedirect, Http404
from .models import Pergunta, Alternativa


# Create your views here.
'''
def index(request):
    lista_perguntas = Pergunta.objects.all()
    context = {'lista_perguntas': lista_perguntas, }
    return render(request, 'enquetes/index.html', context)

class IndexView(generic.ListView):
    template_name = 'enquetes/index.html'
    context_object_name = 'lista_perguntas'
    def get_queryset(self):
        return Pergunta.objects.order_by('-data_pub')

'''

class IndexView(View):
    def get(self, request, *args, **kwargs):
        # lista_perguntas = Pergunta.objects.order_by('-data_pub')
        lista_perguntas = Pergunta.objects.filter(
            data_encerramento__gte = timezone.now()
        ).filter(
            data_pub__lte = timezone.now()
        ).order_by('data_pub')
        contexto = {'lista_perguntas': lista_perguntas, }
        return render(request, 'enquetes/index.html', contexto)


class EncerradasView(View):
    def get(self, request, *args, **kwargs):
        # lista_perguntas = Pergunta.objects.order_by('-data_pub')
        lista_perguntas = Pergunta.objects.filter(data_encerramento__lt = timezone.now()).order_by('data_pub')
        contexto = {'lista_perguntas': lista_perguntas, }
        return render(request, 'enquetes/encerradas.html', contexto)

'''
def detalhes(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
    return render(request, 'enquetes/detalhes.html', {'pergunta':pergunta})


class DetalhesView(generic.DetailView):
    model = Pergunta
    template_name = 'enquetes/detalhes.html'
'''

class DetalhesView(View):
    def get(self, request, *args, **kwargs):
        pergunta = get_object_or_404(Pergunta, pk=kwargs['pk'])
        if pergunta.data_pub > timezone.now():
            raise Http404('Nenhuma pergunta com tal identificação.')
        return render(request, 'enquetes/detalhes.html', {'pergunta':pergunta})

'''
def votacao(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
    try:
        id_alternativa = request.POST['escolha']
        alt_selecionada = pergunta.alternativa_set.get(pk=id_alternativa)
    except (KeyError, Alternativa.DoesNoteExist):
        contexto = {
            'pergunta':pergunta,
            'error': 'Você precisa selecionar uma alternativa'
        }
        return render(request, 'enquetes/detalhes.html', contexto)
    else:
        alt_selecionada.quant_votos += 1
        alt_selecionada.save()
        return HttpResponseRedirect(reverse('enquetes:resultado', args=(pergunta.id,)))
'''

class VotacaoView(View):
    def post(self, request, *args, **kwargs):
        pergunta = get_object_or_404(Pergunta, pk=kwargs['pk'])
        try:
            id_alternativa = request.POST['escolha']
            alt_selecionada = pergunta.alternativa_set.get(pk=id_alternativa)
        except (KeyError, Alternativa.DoesNotExist):
            contexto = {
                'pergunta':pergunta,
                'error': 'Você precisa selecionar uma alternativa'
            }
            return render(request, 'enquetes/detalhes.html', contexto)
        else:
            alt_selecionada.quant_votos += 1
            alt_selecionada.save()
            return HttpResponseRedirect(reverse('enquetes:resultado', args=(pergunta.id,)))

'''
def resultado(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
    return render(request, 'enquetes/resultado.html', {'pergunta':pergunta})


class ResultadoView(generic.DetailView):
    model = Pergunta
    template_name = 'enquetes/resultado.html'
'''


class ResultadoView(View):
    def get(self, request, *args, **kwargs):
        pergunta = get_object_or_404(Pergunta, pk=kwargs['pk'])
        return render(request, 'enquetes/resultado.html', {'pergunta':pergunta})

principal/views.py
from django.shortcuts import render
from django.views import View


class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'principal/index.html')

caridade/templates/caridade/detalhes.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhe evento</title>
</head>
<body>
    <h1>Evento de caridade</h1>
    <h3>Detalhes da enquetes #{{ evento.id }}</h3>
    <h3>{{ evento.nome }}</h3>
    <ul>
        {% for item in evento.item_set.all %}
        <label for="item{{ forloop.counter }}">{{ item.descricao }} -- Preço: R$ {{ item.valor | floatformat:2 }}</label><br/>
        {% endfor %}
    </ul>
    <hr/>
    <a href= "{% url 'caridade:index' %}">Voltar</a>
 </body>
</html>

caridade/templates/caridade/index.html
<html>
    <head>
        <title>Evento de Caridade</title>
    </head>
    <body>
        <h1>Evento de Caridade Q Ajuda</h1>
        <hr/>
        {% if lista_eventos %}
            <ul>
                {% for evento in lista_eventos %}
                    <li><a href="{% url 'caridade:detalhes' evento.id %}">
                        {{ evento.nome }}</a> data início: {{ evento.data_inicio }} data de término: {{ evento.data_fim }} - organizado por {{ evento.usuario.username }}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <h3>Nenhum evento disponível no momento</h3>
        {% endif %}

        <hr/>
        &copy; DSWeb/TADS/CNAT/IFRN 2023
    </body>
</html>

enquetes/templates/enquetes/detalhes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App Enquetes</title>
</head>
<body>
    <h1>Aplicação de Enquetes</h1>
    <h3>Detalhes da enquetes #{{ pergunta.id }}</h3>
    <h3>{{ pergunta.enunciado }}</h3>
    <ul>
        {% for alt in pergunta.alternativa_set.all %}
            <li>{{ alt.texto }}</li>
        {% endfor %}
    </ul>
</body>
</html>

enquetes/templates/enquetes/encerradas.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App Enquetes</title>
</head>
<body>
    <h1>Aplicação de Enquetes</h1>
    <h2>Listagem das Enquetes ENCERRADAS</h2>
    {% if lista_perguntas %}
        <ul>
            {% for pergunta in lista_perguntas %}
                <li><a href="{% url 'enquetes:detalhes' pergunta.id %}">
                    {{ pergunta.enunciado }}
                </a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>Nenhuma enquete encerrada até o momento.</h3>
    {% endif %}
    <hr/>
    <a href="{% url 'enquetes:index' %}">Voltar</a>
</body>
</html>

enquetes/templates/enquetes/index.html
<!DOCTYPE html>
{% load static %}

<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = "stylesheet" type="text/css" href="{% static 'enquetes/css/styles.css' %}">
    <title>App Enquetes</title>
</head>
<body>
    <h1><img src="{% static 'enquetes/imgs/enquetes.png' %}" width="50">
        Aplicação de Enquetes</h1>
    {% if lista_perguntas %}
        <ul>
            {% for pergunta in lista_perguntas %}
                <li><a href="{% url 'enquetes:detalhes' pergunta.id %}">
                    {{ pergunta.enunciado }}
                </a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>Nenhuma enquete cadastrada até o momento.</h3>
    {% endif %}
    <hr/>
    <a href="{% url 'enquetes:encerradas' %}">Listar enquetes encerradas</a>
</body>
</html>

enquetes/templates/enquetes/resultado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App Enquetes</title>
</head>
<body>
    <h1>Aplicação de Enquetes</h1>
    <h3>Detalhes da enquetes #{{ pergunta.id }}</h3>
    <h3>{{ pergunta.enunciado }}</h3>
    <ul>
        {% for alt in pergunta.alternativas_ordenadas %}
            <li>{{ alt.texto }} -- {{ alt.quant_votos }} voto{{ alt.quant_votos | pluralize }} -- {{ alt.porcentagem | floatformat:0 }}% </li>
        {% endfor %}
    </ul>
    <hr/>
    <a href= "{% url 'enquetes:index' %}">Voltar</a>
    <a href= "{% url 'enquetes:detalhes' pergunta.id %}">Votar novamente!</a>
 </body>
</html>

principal/templates/principal/index.html
<html>
    <head>
        <title>Projeto Yuri Thairony</title>
    </head>
    <body>
        <h1>Aplicações da Disciplina de DSWeb 2023.1</h1>
        <hr/>
        <ul>
            <li><a href="{% url 'enquetes:index' %}">Aplicação de Enquetes</a></li>
            <li><a href="{% url 'caridade:index' %}">Aplicação Evento de Caridade</a></li>
        </ul>
    </body>
</html>